#!/usr/bin/env python3

# -*- coding: utf-8 -*-
# Copyright (C) 2025 Antoine DELAPORTE
# Licensed under the EUPL v.1.2
# See LICENSE file or https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

from instreq import install_requirements
install_requirements("/srv/hapimie/hapimie/requirements.txt","/srv/pip-install")
import sys
sys.path.insert(0, "/srv/pip-install")

from pano import Pano
from zapiz import Zapiz

import os,argparse,configparser

parser = argparse.ArgumentParser(
    description="Happy l'api amie de l'AMI"
    )
parser.add_argument("--cfgfile", default="/usr/local/etc/hapimie.cfg", help="Specify a config file")
parser.add_argument("--name", default="default", help="Specify a part of a config file")

# 🧩 Analyse des arguments
args,unknown = parser.parse_known_args()

# ⚠️ Gestion des arguments inconnus
if unknown:
    print("❌ Arguments inconnus :", ' '.join(unknown))
    parser.print_help()
    sys.exit(1)


cfg={}
cfg['API_PORT']= 8888
cfg['API_HOST']= "0.0.0.0"
cfg['AMI_HOST']= "127.0.0.1"
cfg['API_PATH']= "/api"
cfg['AMI_PORT']= 5038
cfg['AMI_USER']= "asterisk"
cfg['AMI_PASS']= "Sangoku"
cfg['MAX_RETRIES']= 3
cfg['RETRY_DELAY']= 3  # secondes

cfg['SECRET_KEY']= "your-secret-key"
cfg['ALGORITHM']= "HS256"
cfg['TOKEN_EXPIRY_HOURS']= 2
cfg['SENTRY_DSN']=None
cfg['SENTRY_RELEASE']='Unknown'
cfg['OIDC_CLIENT_ID']=None
cfg['OIDC_CLIENT_SECRET']=None
cfg['OIDC_ISSUER']=None
cfg['OIDC_AUTH_URL']=None
cfg['OIDC_TOKE_URL']=None
cfg['OIDC_REDI_URL']=None
cfg['OIDC_JWKS_URL']=None
cfg['OIDC_USIN_URL']=None

cfg['USER_CSVFILE']=None

cfg['HAPACL_FULL']=None
cfg['HAPACL_Status']=None

if os.path.exists(args.cfgfile) and os.path.isfile(args.cfgfile):
    config= configparser.ConfigParser()
    config.optionxform=str
    config.read(args.cfgfile)
    if args.name not in config.keys():
        print(f'No {args.name} in {args.cfgfile}... OOOoooops')
        sys.exit(1)
    for elem in cfg.keys():
        if elem not in config[args.name]:
            continue
        cfg[elem]=config[args.name][elem]
elif os.getenv('AMI_HOST',None):
    for elem in cfg.keys():
        cfg[elem]=os.getenv(elem,cfg[elem])
else:
    print(f'No {args.cfgfile}.... Kouik')
    sys.exit(1)


for elem in ['API_PORT','AMI_PORT','MAX_RETRIES','RETRY_DELAY']:
    i=cfg[elem]
    cfg[elem]=int(i)
for elem in ['TOKEN_EXPIRY_HOURS']:
    i=cfg[elem]
    cfg[elem]=float(i)

if 'SENTRY_DSN' in cfg.keys():
    print("Sentry Enabling")
    import sentry_sdk
    from sentry_sdk.types import Event, Hint

    IGNORED_EXCEPTIONS = (
        ConnectionResetError,
        ConnectionAbortedError,
        BrokenPipeError,
        #asyncio.TimeoutError,
        )

    def sentry_before_send(event: Event, hint: Hint): # -> Event | None:
        if "exc_info" in hint:
            exc_type, exc_value, tb = hint["exc_info"]

            # Ignore exceptions TCP classiques
            if issubclass(exc_type, IGNORED_EXCEPTIONS):
                return None

            # Ignore erreurs AMI connues
            msg = str(exc_value)

            if "TCPTransport closed=True" in msg:
                return None

            if "Connection Lost" in msg:
                return None

        return event

    sentry_sdk.init(
        dsn=cfg['SENTRY_DSN'],
        environment=cfg['SENTRY_RELEASE'],
        release="hapimie@3.0",
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        before_send=sentry_before_send
        )

asti=Pano(host=cfg['AMI_HOST'], port=cfg['AMI_PORT'], login=cfg['AMI_USER'], password=cfg['AMI_PASS'])

app = Zapiz(
    host=cfg['API_HOST'],
    port=cfg['API_PORT'],
    title="Hapimie",
    description="Happy l'api amie de l'AMI",
    version="0.0.3",
    docs_url="/docs",               # URL de Swagger
    redoc_url="/redoc",             # URL de Redoc
    openapi_url="/openapi.json",    # Spécification OpenAPI
    oidc_client_id=cfg['OIDC_CLIENT_ID'],
    oidc_client_secret=cfg['OIDC_CLIENT_SECRET'],
    oidc_issuer=cfg['OIDC_ISSUER'],
    oidc_auth_url=cfg['OIDC_AUTH_URL'],
    oidc_toke_url=cfg['OIDC_TOKE_URL'],
    oidc_redi_url=cfg['OIDC_REDI_URL'],
    oidc_jwks_url=cfg['OIDC_JWKS_URL'],
    oidc_usin_url=cfg['OIDC_USIN_URL'],
    user_csvfile=cfg['USER_CSVFILE'],
    sentry=cfg['SENTRY_DSN'],
    secret_key=cfg['SECRET_KEY'],
    startup=asti.startup
    )


def form_home(varSession,params={}):
#, user=Depends(get_user_from_cookie)):
    print(f"🈁 Ici on est")

    return ({'template':"welcome.html",'varSession': varSession })

def form_view(varSession,params={}):
    #varSession={}
    print(varSession)
    nom=params.get('nom',None)
    ret={}

    print(f"🎯 Auth, et cmd :{nom}")
    ret={
        "command_name": nom,
        "login": varSession["nickname"],
        "gecos": varSession["email"],
        #"sentry_dsn": cfg.get("SENTRY_DSN"),
        }
    return ({'template':"json.html",'varSession': ret })

async def api_help_exec(varSession,params={}):
    #form = await request.form()
    #user = request.session.get("user")
    data=varSession['form']

    if 'Action' in data.keys():
        ret=await asti.action(data)
        response = {
            "Response": "Success",
            "Message": f"Commande {data['Action']} exécutée",
            "Data": data,
            'Retour': ret
            }
    else:
        response = {
            "Response": "Failure",
            "Message": f"Non logué ou pas d'action",
            "Data": data,
            'Retour': {}
            }

    return(response)

def form_help(varSession,params={}):
    return ({'template':"help.html",'varSession': varSession })

def form_endpoints(varSession,params={}):
    #return ({'template':'endpoints.html','varSession':varSession})
    return ({'template':'endpoints.html','nom':params.get('nom',""),"groupe":params.get('groupe',"")})

def form_help_detail(varSession,params={}):
    print('🔎help The detail')
    return({'template':'help-detail2.html',"help":params.get('nom',None)})

async def api_help(varSession,params={}):
    """
    Renvoie la doc de l'AMI
    Si on precise un parametre, c'est ce parametre sur lequel on renverra la doc
    """
    print('🆘 Help section')
    if 'command' in params.keys():
        command=params['command']
    else:
        command=None
    ret=await asti.help(command)
    return(ret)

#async def get_status(auth=Depends(get_auth_info)):
#async def get_status(request: Request):
async def api_status(varSession,params={}):
    """
    Renvoie le status.... hmmmm ca ressemble a un coreshowchannel
    """

    ret=await asti.channels()
    ## TODO gerer les droits ici
    return(ret)

#async def hangup(request: Request,auth=Depends(get_auth_info)):
async def api_hangup(varSession,params={}):
    """
    Permet de raccrocher le channel en cours
    """
    chan=params.get("channel_id",None)
    ret=await asti.channel_del(chan)
    if ret is None:
        #raise HTTPException(status_code=508)
        return(None)
    return(ret)

async def api_endpoints(varSession,params={}):
    ret=await asti.endpoints()
    return(ret)

async def api_endpointPerGrp(varSession,params={}):
    ret=await asti.endpointsGrp()
    return(ret)

#def ligne_view(request: Request, user=Depends(get_user_from_cookie)):
#def ligne_view(request: Request):
def form_ligne(varSession,params={}):
    refresh_interval = 1000  # en millisecondes

    return ({'template':"ligne.html",'varSession': varSession,'template_data':{'refresh_interval':refresh_interval }})

async def api_queues(varSession,params={}):
    ret=await asti.queues()
    return(ret)

#@declare_path(app,"get", f"{cfg['API_PATH']}/coreshowchannels")
#async def get_coreshowchannels():
#    """
#    Affiche les channels en cours
#    """
#    hero="CoreShowChannels"
#    return(trichan(await action(hero)))

#async def queue(request: Request, user=Depends(get_user_from_cookie)):
async def form_queues(varSession,params={}):
    """
    Affichage des queues
    """
    refresh_interval = 5000  # en millisecondes

    return ({'template':"queue.html",'varSession': varSession,'template_data':{'refresh_interval':refresh_interval }})

async def api_dbGet(varSession,params={}):
    """
    On affiche le contenu de la db
    """
    key=params.get('path',None)
    ret=await asti.db_get(key)
    return(ret)


#async def dbview(request: Request, user=Depends(get_user_from_cookie)):
async def form_dbview(varSession,params={}):
    """
    Affichage pour lecture, modification et suppression d'enregistrement dans la DB d'Asterisk
    """
    return ({'template':"dbview.html",'varSession': varSession})

#async def db_put(request: Request,user=Depends(get_user_from_cookie)):
async def api_dbPut(varSession,params={}):
    data = dict(form)
    data["Action"] = form.get("Action")

    family, key = data['Attribut'].split("/", 1)
    hero={'Action':'DbPut','family':family,'key':key,'val':data['Val']}

    ret=await action(hero)

    response = {
        "Response": "Success",
        "Message": f"Commande {data['Action']} exécutée",
        "Data": data,
        "Action": hero,
        'Retour': ret
    }
    tocache('database',{},0.1)

    return(response)

#async def db_del(request: Request,user=Depends(get_user_from_cookie)):
async def api_Dbdel(varSession,params={}):
    form = await request.form()
    user = request.session.get("user")
    data = dict(form)
    data["Action"] = form.get("Action")

    family, key = data['Attribut'].split("/", 1)
    hero={'Action':'DbDel','family':family,'key':key}

    ret=await action(hero)

    response = {
        "Response": "Success",
        "Message": f"Commande {data['Action']} exécutée",
        "Data": data,
        "Action": hero,
        'Retour': ret
    }
    tocache('database',{},0.1)

    return(response)

#async def dial_page(request: Request, login=Depends(get_user_from_cookie)):
async def form_dial(varSession,params={}):
    return ({'template':"dial.html",'varSession': varSession})


async def showtrack(varSession,params={}):
    user = request.session.get("user")
    data = await request.json()

    return(trackeurAMI)

#async def dial_api(request: Request, user=Depends(get_user_from_cookie)):
async def dial_api(varSession,params={}):
    data = await request.json()
    user = request.session.get("user")
    appellant = data.get("appellant")
    numero = data.get("numero")

    ti=f'{appellant}-{numero}'
    if ti in trackeurAMI['Originate'].keys():
        print("Oulla c'est le dawa je ne sais pas encore gerer les bis,alors je raccrocerais l'autre et je relancerais")
        print(f"Va falloire couper ca : {trackeurAMI['Originate'][ti]['Channel']}")
    ti=f'Hapimie-{appellant}-{numero}-{time()}'
    trackeurAMI['Originate'][ti]={}
    hero = {'Action': 'Originate','Channel': f'Local/{appellant}@internal', 'Exten': numero, 'Context': 'internal', 'Priority': 1, 'CallerId':f'Mon ami {appellant}', 'Async':'false','ChannelId': ti }
    ret=await action(hero)
    pprint(ret)
    
    sleep(2)
    print("show nous le trackeur impitoyable")
    print(trackeurAMI['Originate'][ti])
    if ti in trackeurAMI['Originate'].keys():
        cha=trackeurAMI['Originate'][ti]

    return {"status": ret['Response'], "login": user['login'], "appellant": appellant, "numero": numero, 'full':ret, 'channel': cha}

def funNull(varSession=None,params=None):
    1

app.api_add("/",form_home),
app.api_add("/json",form_view,acl=cfg['HAPACL_FULL']),
app.api_add("/json/{nom}",form_view,acl=cfg['HAPACL_FULL']),
app.api_add("/help",form_help),
app.api_add("/help/{nom}",form_help_detail),
app.api_add("/ligne",form_ligne,acl=cfg['HAPACL_Status']),
app.api_add("/endpoints",form_endpoints,acl=cfg['HAPACL_Status']),
app.api_add("/endpoints/{nom}",form_endpoints,acl=cfg['HAPACL_Status']),
app.api_add("/endpoints/{nom}/{groupe}",form_endpoints,acl=cfg['HAPACL_FULL']),
app.api_add("/queue",form_queues,acl=cfg['HAPACL_Status']),
app.api_add("/dbview",form_dbview,acl=cfg['HAPACL_FULL']),
#    app.api_add("/dial", dial_page),
# app.api_add("/favicon.ico",funNull),
app.api_add('/favicon.ico',funNull,file="static/favicon.ico")


app.api_add(f"{cfg['API_PATH']}/help",api_help,daType='json')
app.api_add(cfg['API_PATH']+"/help/{command}",api_help,daType='json')
app.api_add(f"{cfg['API_PATH']}/status",api_status,daType='json',acl=cfg['HAPACL_Status'])
app.api_add(f"{cfg['API_PATH']}/queue",api_queues,daType='json',acl=cfg['HAPACL_Status'])
app.api_add(f"{cfg['API_PATH']}/endpoints",api_endpoints,daType='json',acl=cfg['HAPACL_Status'])
app.api_add(f"{cfg['API_PATH']}/endpointPerGrp",api_endpointPerGrp,daType='json',acl=cfg['HAPACL_Status'])
app.api_add(f"{cfg['API_PATH']}/dbGet",api_dbGet,daType='json',acl=cfg['HAPACL_FULL'])
app.api_add(f"{cfg['API_PATH']}/dbGet/"+"{path:path}",api_dbGet,daType='json',acl=cfg['HAPACL_FULL'])
#    app.api_add(f"{cfg['API_PATH']}/myphones",get_myphones,daType='json')
#    app.api_add(f"{cfg['API_PATH']}/trackeur",showtrack,daType='json')

app.api_add(cfg['API_PATH']+"/help-exec",api_help_exec,daType='json',verb="POST",acl=cfg['HAPACL_FULL']) #POST
app.api_add(cfg['API_PATH']+"/HangUp",api_hangup,daType='json',verb="POST",acl=cfg['HAPACL_FULL']) # POST
#    app.api_add(cfg['API_PATH']+"/dbPut",db_put,daType='json',verb="POST") # POST
#    app.api_add(cfg['API_PATH']+"/dbDel",db_del,daType='json',verb="POST") # POST
#    app.api_add(f"{cfg['API_PATH']}/dial",dial_api,daType='json',verb="POST") # POST



##########################################################################################

#if __name__ == "__main__":
#    import uvicorn
#    app.add_middleware(
#        CORSMiddleware,
#        allow_origins=["*"],  # ou ["http://localhost:3000"]
#        allow_credentials=True,
#        allow_methods=["*"],
#        allow_headers=["*"],
#        )
#    uvicorn.run(app, host=cfg['API_HOST'], port=cfg['API_PORT'])

if __name__ == "__main__":
    app.run()
